# Generated by Django 6.0 on 2025-12-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=100)),
                ('experience', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('rating', models.FloatField(default=0)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
